services:
  autoextract:
    build: .
    container_name: autoextract
    volumes:
      - /mnt/Downloads/Transmission/Completed:/Watch
      - /mnt/Downloads/Transmission/Temp:/ExtractFolder  #optional
      - /home/danhelgeland/Documents/log:/LogFolder  #optional
    environment:
      - INTERVAL=3600
      - TZ=Europe/Oslo
